<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" tests="2" failures="1" timestamp="13 Feb 2018 17:25:01 GMT" time="0.053" errors="0">
  <testcase name="workingTest" time="0.006" classname="ZainsTest"/>
  <testcase name="zainsTest" time="0.02" classname="ZainsTest">
    <failure type="java.net.MalformedURLException">
      <![CDATA[java.net.MalformedURLException
at java.net.URL.<init>(URL.java:627)
at java.net.URL.<init>(URL.java:490)
at java.net.URL.<init>(URL.java:439)
at ZainsTest.zainsTest(ZainsTest.java:19)
Caused by: java.lang.NullPointerException
at java.net.URL.<init>(URL.java:532)
... 32 more
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- zainsTest -->
</testsuite>
